import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "@/component/layout/Footer";


export const metadata: Metadata = {
  title: "Ameer Hamza Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
